export const games = [
  {
    slug: 'toguz-korgool',
    title: 'Toguz Korgool',
    titleRu: 'Тогуз Коргоол',
    titleDe: 'Toguz Korgool',
    origin: 'Central Asia',
    originRu: 'Центральная Азия',
    originDe: 'Zentralasien',
    players: '2',
    duration: '20–40 min',
    difficulty: 2,
    description: {
      en: 'Ancient mancala-type game of the Kyrgyz nomads. Capture stones by landing on even-numbered pits.',
      ru: 'Древняя игра кыргызских кочевников. Захватывай камешки, попадая на чётные лунки соперника.',
      de: 'Altes Mankalaspiel der kirgisischen Nomaden. Steine durch gerade Mulden des Gegners erbeuten.',
    },
    tags: ['strategy', 'mancala', 'central-asia'],
    available: true,
  },
  {
    slug: 'mangala',
    title: 'Mangala',
    titleRu: 'Мангала',
    titleDe: 'Mangala',
    origin: 'Middle East',
    originRu: 'Ближний Восток',
    originDe: 'Naher Osten',
    players: '2',
    duration: '10–20 min',
    difficulty: 1,
    description: {
      en: 'Ancient strategy game of the Middle East. Sow stones and capture by creating groups of 2 or 4.',
      ru: 'Древняя стратегическая игра Ближнего Востока. Раскладывай камешки и захватывай группами по 2 или 4.',
      de: 'Altes Strategiespiel des Nahen Ostens. Steine säen und durch Gruppen von 2 oder 4 erbeuten.',
    },
    tags: ['strategy', 'mancala', 'middle-east'],
    available: true,
  },
  {
    slug: 'oware',
    title: 'Oware',
    titleRu: 'Овари',
    titleDe: 'Oware',
    origin: 'West Africa',
    originRu: 'Западная Африка',
    originDe: 'Westafrika',
    players: '2',
    duration: '15–30 min',
    difficulty: 2,
    description: {
      en: 'Ancient West African strategy game. Capture stones by landing on pits of 2 or 3. Beware the Grand Slam!',
      ru: 'Древняя стратегическая игра Западной Африки. Захватывай камешки попадая на лунки с 2 или 3 камешками. Остерегайся Гранд Слэма!',
      de: 'Altes westafrikanisches Strategiespiel. Steine durch Landen auf Mulden mit 2 oder 3 erbeuten. Vorsicht vor dem Grand Slam!',
    },
    tags: ['strategy', 'mancala', 'africa'],
    available: true,
  },
  {
    slug: 'hnefatafl',
    component: null,
    title: 'Hnefatafl',
    titleRu: 'Хнефатафль',
    titleDe: 'Hnefatafl',
    origin: 'Scandinavia',
    originRu: 'Скандинавия',
    originDe: 'Skandinavien',
    players: '2',
    duration: '20–60 min',
    difficulty: 3,
    description: {
      en: 'Viking strategy game of asymmetric warfare. Attackers vs defenders — can the king escape?',
      ru: 'Стратегическая игра викингов с асимметричными сторонами. Атакующие против защитников.',
      de: 'Wikinger-Strategiespiel mit asymmetrischen Seiten. Angreifer gegen Verteidiger.',
    },
    tags: ['strategy', 'asymmetric', 'europe'],
    available: false,
  },
  {
    slug: 'surakarta',
    component: null,
    title: 'Surakarta',
    titleRu: 'Суракарта',
    titleDe: 'Surakarta',
    origin: 'Southeast Asia',
    originRu: 'Юго-Восточная Азия',
    originDe: 'Südostasien',
    players: '2',
    duration: '10–30 min',
    difficulty: 2,
    description: {
      en: 'Unique game with looping tracks. Pieces travel around corner loops to capture opponents.',
      ru: 'Уникальная игра с петлями. Фигуры захватывают, проезжая через угловые петли.',
      de: 'Einzigartiges Spiel mit Schleifen. Figuren reisen durch Eckschleifen um zu schlagen.',
    },
    tags: ['strategy', 'southeast-asia'],
    available: false,
  },
];

export function getGame(slug) {
  return games.find(g => g.slug === slug);
}

export function getAvailableGames() {
  return games.filter(g => g.available);
}